In [28]:
import numpy as np

arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [29]:
print(type(arr1))

<class 'numpy.ndarray'>


means 1D array

In [30]:
print(arr1.shape)#3 cols

(3,)


In [10]:
print(arr1[2])

3


In [11]:
arr1[2]=5
arr1 #prints array elements

array([1, 2, 5])

In [13]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
print(arr2.shape)#2 rows 3 columns

(2, 3)


In [17]:
arr2[0,2] #accessing element at 0th row and 2 column

3

In [22]:
arr2[0][-1] #we can address in reverse too like -1,-2,-3

3

In [26]:
arr=["China","Pakistan","USA","Mexico"]
arr

['China', 'Pakistan', 'USA', 'Mexico']

In [32]:
arrR=np.arange(0,20,2)#0 2 4 ... 18 (20 not included counts upto 20)
arrR

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
arr=np.random.rand(3,4)
arr

array([[0.88623725, 0.66865936, 0.2912587 , 0.00281343],
       [0.79001723, 0.89910895, 0.38072337, 0.33475995],
       [0.63221217, 0.17440176, 0.90216123, 0.11360874]])

In [37]:
print(np.zeros(10))#10 rows in a row
print("\n")
print(np.zeros((2,3)))#zeros in 2 rows 3 cols

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]]


In [38]:
print(np.ones(10))#same as above but for 1s

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [40]:
arr=[6,2,3]
print(np.repeat(arr,3))#repitition of arr 3 times

[6 6 6 2 2 2 3 3 3]


In [43]:
#generating a 6 2 3 pattern using tile then repeating it thrice
print(np.tile(arr,3))

[6 2 3 6 2 3 6 2 3]


In [45]:
#3x3 identity matrix in 2 ways
# identity_matrix = np.identity(3)
id=np.eye(3)
# identity_matrix
id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
# prompt: generate a matrix having diagonal 1 2 3
# diagonal_elements = [1, 2, 3]
# size = len(diagonal_elements)
# matrix = np.zeros((size, size), dtype=int)  # Initialize a matrix of zeros

# for i in range(size):
#   matrix[i, i] = diagonal_elements[i]

# matrix

np.diag([1,2,3]) #SAME WORK AS ABOVE CODE

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [49]:
arr=np.random.rand(5,5)
arr

array([[0.35820293, 0.84213269, 0.81891561, 0.69878061, 0.66345575],
       [0.97347717, 0.45432185, 0.2347597 , 0.71784758, 0.03023978],
       [0.51234942, 0.62386924, 0.16273396, 0.05208801, 0.46792003],
       [0.81963803, 0.80364048, 0.97858111, 0.90395297, 0.32278301],
       [0.03287447, 0.55011576, 0.56517123, 0.03178637, 0.77459376]])

In [51]:
#identifyng diag
# arr.diagonal()
np.diag(arr) #same as above

array([0.35820293, 0.45432185, 0.16273396, 0.90395297, 0.77459376])

In [55]:
arr.ndim #dimension

2

In [56]:
arr.shape

(5, 5)

In [ ]:
arr.size #total elements

In [60]:
#generating random integers b/w -10 to 10 and we will generate 4 of those
np.random.randint(-10,10,4)

array([ 7, -8,  8,  2])

In [61]:
np.random.rand(2,10,4)
#3D array of 10 rows and 4 cols and 2 layers made

array([[[0.62465969, 0.69455312, 0.33034633, 0.62838542],
        [0.22901855, 0.5630655 , 0.0245316 , 0.83046814],
        [0.463344  , 0.22725262, 0.91971632, 0.09986412],
        [0.51662022, 0.9825022 , 0.31843724, 0.32198077],
        [0.87775823, 0.42063751, 0.91101038, 0.50279717],
        [0.21640143, 0.88189926, 0.17539193, 0.66369657],
        [0.57770896, 0.81832888, 0.33928942, 0.72102018],
        [0.36536161, 0.97674955, 0.12801969, 0.45404916],
        [0.15767547, 0.81332004, 0.83090278, 0.63218002],
        [0.40854247, 0.50556602, 0.28442697, 0.32867873]],

       [[0.63349396, 0.95673853, 0.51796791, 0.95956737],
        [0.51497067, 0.68985685, 0.87156755, 0.08328273],
        [0.31952653, 0.28364717, 0.91883894, 0.04511288],
        [0.50261288, 0.15192881, 0.23957311, 0.08135831],
        [0.23555414, 0.35580125, 0.58727044, 0.69134492],
        [0.75234061, 0.17009754, 0.96067877, 0.13255435],
        [0.74135952, 0.68339521, 0.67861021, 0.75331302],
        [0.0

In [62]:
arr+10 #adding 10 to original arr

array([[10.35820293, 10.84213269, 10.81891561, 10.69878061, 10.66345575],
       [10.97347717, 10.45432185, 10.2347597 , 10.71784758, 10.03023978],
       [10.51234942, 10.62386924, 10.16273396, 10.05208801, 10.46792003],
       [10.81963803, 10.80364048, 10.97858111, 10.90395297, 10.32278301],
       [10.03287447, 10.55011576, 10.56517123, 10.03178637, 10.77459376]])

In [64]:
arr*10

array([[3.58202932, 8.42132687, 8.18915612, 6.98780609, 6.63455751],
       [9.73477172, 4.5432185 , 2.347597  , 7.17847577, 0.30239775],
       [5.12349417, 6.23869245, 1.62733961, 0.52088009, 4.67920029],
       [8.19638029, 8.0364048 , 9.78581106, 9.03952966, 3.22783013],
       [0.32874471, 5.50115761, 5.65171225, 0.31786369, 7.74593758]])

In [65]:
arr/2

array([[0.17910147, 0.42106634, 0.40945781, 0.3493903 , 0.33172788],
       [0.48673859, 0.22716093, 0.11737985, 0.35892379, 0.01511989],
       [0.25617471, 0.31193462, 0.08136698, 0.026044  , 0.23396001],
       [0.40981901, 0.40182024, 0.48929055, 0.45197648, 0.16139151],
       [0.01643724, 0.27505788, 0.28258561, 0.01589318, 0.38729688]])

In [66]:
#applying exponential on original log can also be applied
np.exp(arr)

array([[1.43075594, 2.32131233, 2.26803907, 2.01129865, 1.94149006],
       [2.64713301, 1.57510486, 1.26460485, 2.05001596, 1.03070164],
       [1.66920826, 1.86613462, 1.17672359, 1.05346845, 1.59666971],
       [2.26967813, 2.23365773, 2.66067834, 2.46934508, 1.38096567],
       [1.03342081, 1.73345367, 1.75974907, 1.03229695, 2.16971052]])

In [67]:
np.sin(arr) #tan/cos/sin can also be applied

array([[0.3505918 , 0.74606491, 0.73040561, 0.64328457, 0.6158432 ],
       [0.82684637, 0.43885306, 0.23260928, 0.65776494, 0.03023517],
       [0.49022634, 0.5841799 , 0.16201665, 0.05206446, 0.45103087],
       [0.73089884, 0.71988768, 0.82970618, 0.78577799, 0.31720707],
       [0.03286855, 0.52278591, 0.53556042, 0.03178102, 0.69942579]])

In [70]:
#summing all the values within arr
np.sum(arr)

13.39423150636588

In [75]:
#rounding off the sum to 2 deci places
round(np.sum(arr),2)
# round(np.sum(arr)) gives 13 as ans

13.39

In [79]:
#summation of rows
(np.sum(arr,axis=1)) #axis=0 for cols summation

array([3.38148759, 2.41064608, 1.81896066, 3.82859559, 1.95454158])

In [80]:
#finding min within arr
np.min(arr)

0.030239775279961467

In [85]:
np.max(arr)
np.max(arr,axis=1) #max in each row

array([0.84213269, 0.97347717, 0.62386924, 0.97858111, 0.77459376])

In [87]:
np.min(arr,axis=0) #min in each col

array([0.03287447, 0.45432185, 0.16273396, 0.03178637, 0.03023978])

In [86]:
print(arr)

[[0.35820293 0.84213269 0.81891561 0.69878061 0.66345575]
 [0.97347717 0.45432185 0.2347597  0.71784758 0.03023978]
 [0.51234942 0.62386924 0.16273396 0.05208801 0.46792003]
 [0.81963803 0.80364048 0.97858111 0.90395297 0.32278301]
 [0.03287447 0.55011576 0.56517123 0.03178637 0.77459376]]


In [84]:
np.mean(arr)

0.5357692602546352

In [88]:
np.mean(arr,axis=0) #mean of each row

array([0.5393084 , 0.654816  , 0.55203232, 0.48089111, 0.45179847])

In [89]:
np.median(arr) #same as above for finding median of each row or col

0.5651712254544207

In [90]:
#standard deviation for whole arr
np.std(arr)

0.3037331077382191

In [94]:
#variance for whole arr
round(np.var(arr),2) #variance is square of std

0.09

In [97]:
#slicing data
arr[0:,2:4] #zeroth row 2rd col and upto 4th col(means till 3 col)

array([[0.81891561, 0.69878061],
       [0.2347597 , 0.71784758],
       [0.16273396, 0.05208801],
       [0.97858111, 0.90395297],
       [0.56517123, 0.03178637]])

In [98]:
#sorting row wise
np.sort(arr,axis=1)

array([[0.35820293, 0.66345575, 0.69878061, 0.81891561, 0.84213269],
       [0.03023978, 0.2347597 , 0.45432185, 0.71784758, 0.97347717],
       [0.05208801, 0.16273396, 0.46792003, 0.51234942, 0.62386924],
       [0.32278301, 0.80364048, 0.81963803, 0.90395297, 0.97858111],
       [0.03178637, 0.03287447, 0.55011576, 0.56517123, 0.77459376]])

In [99]:
#sorting col wise
np.sort(arr,axis=0)

array([[0.03287447, 0.45432185, 0.16273396, 0.03178637, 0.03023978],
       [0.35820293, 0.55011576, 0.2347597 , 0.05208801, 0.32278301],
       [0.51234942, 0.62386924, 0.56517123, 0.69878061, 0.46792003],
       [0.81963803, 0.80364048, 0.81891561, 0.71784758, 0.66345575],
       [0.97347717, 0.84213269, 0.97858111, 0.90395297, 0.77459376]])

In [100]:
arr

array([[0.35820293, 0.84213269, 0.81891561, 0.69878061, 0.66345575],
       [0.97347717, 0.45432185, 0.2347597 , 0.71784758, 0.03023978],
       [0.51234942, 0.62386924, 0.16273396, 0.05208801, 0.46792003],
       [0.81963803, 0.80364048, 0.97858111, 0.90395297, 0.32278301],
       [0.03287447, 0.55011576, 0.56517123, 0.03178637, 0.77459376]])

In [101]:
#taking transpose
arr.T

array([[0.35820293, 0.97347717, 0.51234942, 0.81963803, 0.03287447],
       [0.84213269, 0.45432185, 0.62386924, 0.80364048, 0.55011576],
       [0.81891561, 0.2347597 , 0.16273396, 0.97858111, 0.56517123],
       [0.69878061, 0.71784758, 0.05208801, 0.90395297, 0.03178637],
       [0.66345575, 0.03023978, 0.46792003, 0.32278301, 0.77459376]])

In [102]:
#flatten down values into single array
arr.flatten()

array([0.35820293, 0.84213269, 0.81891561, 0.69878061, 0.66345575,
       0.97347717, 0.45432185, 0.2347597 , 0.71784758, 0.03023978,
       0.51234942, 0.62386924, 0.16273396, 0.05208801, 0.46792003,
       0.81963803, 0.80364048, 0.97858111, 0.90395297, 0.32278301,
       0.03287447, 0.55011576, 0.56517123, 0.03178637, 0.77459376])

In [103]:
arr3=np.array([1,3,5])
arr3

array([1, 3, 5])

In [105]:
np.append(arr3,7)

array([1, 3, 5, 7])

In [107]:
np.append(arr3,[7,9,11])

array([ 1,  3,  5,  7,  9, 11])

In [111]:
#inserting at beginning or anywhere
np.insert(arr3,2,[1,1,1])

array([1, 3, 1, 1, 1, 5])

In [116]:
arr3

array([1, 3, 5])

In [117]:
arrN=np.delete(arr3,0)
arrN

array([3, 5])

In [120]:
arrw=np.delete(arr3,[0,1])
arrw

array([5])

In [132]:
#concatenating arrays
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[10,20,30,40],[50,60,70,80]])
# merge=np.concatenate((arr1,arr2))
merge=np.concatenate((arr1,arr2),axis=1)#row wise
merge

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

In [133]:
merge=np.concatenate((arr1,arr2),axis=0)#col wise
merge

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

In [131]:
catV=np.vstack((arr1,arr2)) #no need of axis works for vertical like axis=0
catV
#hstack for row wise (axis=1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

In [134]:
#identifying unique values
arrU=np.array([1,2,2,1,1,4,4,2,4,6,4])
np.unique(arrU)

array([1, 2, 4, 6])

In [136]:
#how many unique values
uniques, counts=np.unique(arrU,return_counts=True)
print(uniques) #displays unique value up
print(counts)  #displays count below

[1 2 4 6]
[3 3 4 1]


In [137]:
#intersection/common
arr1=np.array([1,2,3,4])
arr2=np.array([1,6,7,8,3])
np.intersect1d(arr1,arr2)

array([1, 3])

In [138]:
#UNION
arr1=np.array([1,2,3,4])
arr2=np.array([1,6,7,8,3])
np.union1d(arr1,arr2)

array([1, 2, 3, 4, 6, 7, 8])

In [139]:
#SET DIFFERENCE
arr1=np.array([1,2,3,4])
arr2=np.array([1,6,7,8,3])
np.setdiff1d(arr1,arr2)
#values in arr1-arr2

array([2, 4])

In [140]:
arr1=np.array([1,2,3,4])
arr2=np.array([1,6,7,8,3])
np.setxor1d(arr1,arr2)

array([2, 4, 6, 7, 8])